version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - learn_clojure_lein_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example

volumes:
  learn_clojure_lein_mysql:
